# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param project.hsv.suppressChildGraphs 0
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{d:/Masters/CourseSpring16/SOC/Projects/project2_release/project2_release/Creating an Icon ROM in Vivado/ICON_0.coe}}
read_verilog -library xil_defaultlib {
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/world_map.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/world_if.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/map.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/kcpsm6.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/bot_pgm.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/colorizer.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/proj2demo.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/nexys4_bit_if.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/dtg.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/debounce.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/clk_wiz_0_clk_wiz.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/bot.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/sevensegment.v
  C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/nexys4fpga.v
}
read_edif C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/world_map_part1/world_map.ngc
read_xdc C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/constrs_1/imports/constraints/n4DDRfpga_withvideo.xdc
set_property used_in_implementation false [get_files C:/Users/yadne/Documents/GitHub/pro2_deb/Project2/project_2/project_2.srcs/constrs_1/imports/constraints/n4DDRfpga_withvideo.xdc]

synth_design -top Nexys4fpga -part xc7a100tcsg324-1
write_checkpoint -noxdef Nexys4fpga.dcp
catch { report_utilization -file Nexys4fpga_utilization_synth.rpt -pb Nexys4fpga_utilization_synth.pb }
