# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/world_map.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/bot_pgm.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/world_if.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/map.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/kcpsm6.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/proj2demo.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/sevensegment.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/nexys4_bit_if.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/debounce.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/bot.v
  D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/hdl_part1/nexys4fpga.v
}
read_edif D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/sources_1/imports/world_map_part1/world_map.ngc
read_xdc D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/constrs_1/imports/constraints/n4DDRfpga_novideo.xdc
set_property used_in_implementation false [get_files D:/Documents/PSU/ECE540/Proj2/pro2_deb/Project2/project_2/project_2.srcs/constrs_1/imports/constraints/n4DDRfpga_novideo.xdc]

synth_design -top Nexys4fpga -part xc7a100tcsg324-1
write_checkpoint -noxdef Nexys4fpga.dcp
catch { report_utilization -file Nexys4fpga_utilization_synth.rpt -pb Nexys4fpga_utilization_synth.pb }
